# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 16:09
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
    ]
