# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_auto_20171006_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inn',
            name='inn',
            field=models.BigIntegerField(unique=True),
        ),
    ]
