# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 16:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_auto_20171006_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inn',
            name='inn',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z', 32), code='invalid', message=None)]),
        ),
    ]
