# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_auto_20171006_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfers.Inn'),
        ),
    ]
